# Generated by Django 3.2.5 on 2021-07-25 11:19

from django.db import migrations, models
import tele_order.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promotion_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.SlugField(blank=True, max_length=32, null=True, validators=[tele_order.utils.validators.validate_tag], verbose_name='Тэг ресторана'),
        ),
    ]
