# Generated by Django 3.2.5 on 2021-08-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_restaurant_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID последнего ресторана'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('MANAGER', 'Менеджер'), ('SUPER_ADMIN', 'Супер админ')], default='USER', max_length=30, verbose_name='Роль пользователя'),
        ),
    ]
