# Generated by Django 3.2.5 on 2021-08-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('key', models.PositiveIntegerField(verbose_name='Ключ в словаре')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статичная запись')),
                ('description', models.CharField(max_length=256, verbose_name='Дополнительное поле')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента (Моделька)')),
            ],
            options={
                'verbose_name': 'Статический перевод',
                'verbose_name_plural': 'Статические переводы',
                'db_table': 'static_translation',
            },
        ),
    ]
